add(main): added health check endpoint.
update(pre-deploy): updated steps `Wait for Server Startup` and `Health Check`. The last step will display info about server after startup.

diff --git a/.github/workflows/pre-deploy.yml b/.github/workflows/pre-deploy.yml
--- a/.github/workflows/pre-deploy.yml
+++ b/.github/workflows/pre-deploy.yml
@@ -41,24 +41,36 @@ jobs:
 
       - name: Wait for Server Startup
         run: |
-            for i in {1..5}; do
-              if curl -s -o /dev/null -w "%{http_code}" ${{ secrets.STAGE_BASE_URL }} | grep -q "200"; then
-                echo "Server is up!"
-                break
-              fi
+              for i in {1..5}; do
+                response_code=$(curl -s -o /dev/null -w "%{http_code}" ${{ secrets.STAGE_BASE_URL }}/health_check)
+                if [ "$response_code" -eq 200 ]; then
+                  echo "Server is up!"
+                  break
+                fi
                 echo "Waiting for server..."
                 sleep 5
-            done
-  
+              done
+              if [ "$response_code" -ne 200 ]; then
+                echo "Server did not start in time."
+                exit 1
+              fi
+
+      - name: Install jq
+        run: sudo apt-get install -y jq
+            
+        
       - name: Health Check
         run: |
-            response=$(curl -s -o /dev/null -w "%{http_code}" ${{ secrets.STAGE_BASE_URL }})
-            if [ "$response" -ne 200 ]; then
-                echo "Health check failed with status $response"
-                exit 1
-            else
-                echo "Health check passed!"
-            fi
-
+              response_code=$(curl -s -w "%{http_code}" -o /tmp/health_response.json ${{ secrets.STAGE_BASE_URL }}/health_check)
+              if [ "$response_code" -ne 200 ]; then
+                  echo "Health check failed with status $response_code"
+                  exit 1
+              else
+                  echo "Health check passed!"
+                  echo "Server Health Status:"
+                  cat /tmp/health_response.json | jq .
+              fi
+        
       - name: Cleanup
         run: rm -rf ~/.ssh
+        
