add(workflow): added reusable workflow `Build and Push Image` and used it in `pre_deploy.yml` workflow.

diff --git a/.github/workflows/pre_deploy.yml b/.github/workflows/pre_deploy.yml
--- a/.github/workflows/pre_deploy.yml
+++ b/.github/workflows/pre_deploy.yml
@@ -11,11 +11,11 @@ on:
     branches:
       - main
 
-env:
-  BACKEND_IMAGE_NAME: proxy_management
-  NGINX_IMAGE_NAME: reverse_proxy
-  REGISTRY: ghcr.io
-  BRANCH: main
+# env:
+#   BACKEND_IMAGE_NAME: proxy_management
+#   NGINX_IMAGE_NAME: reverse_proxy
+#   REGISTRY: ghcr.io
+#   BRANCH: main
   
 jobs:
   setup-ssh:
@@ -29,89 +29,123 @@ jobs:
       gh_artifacts_gpg_private: ${{ secrets.GH_ARTIFACTS_GPG_PRIVATE }}
       gh_artifacts_gpg_public: ${{ secrets.GH_ARTIFACTS_GPG_PUBLIC }}
       gpg_id: ${{ secrets.GPG_ID }}
+    
+  build-push-backend-image:
+    uses: ./.github/workflows/build_and_push_image.yml
+    name: Build And Push Backend Image
+    with:
+      registry: ghcr.io
+      image-name: proxy_management
+      context-path: backend
+      dockerfile-path: backend/Dockerfile
+      working-directory: ./backend
+      additional-labels: |
+        org.opencontainers.image.licenses=MIT
+        org.opencontainers.image.description=Image with backend and frontend implementation for proxy management
+      tags: |
+        type=sha
 
-  build-push-image:
-    runs-on:
-      ubuntu-latest
+  build-push-nginx-image:
+    uses: ./.github/workflows/build_and_push_image.yml
+    name: Build And Push Nginx Image
+    with:
+      registry: ghcr.io
+      image-name: reverse_proxy
+      context-path: backend/deploy_config/nginx
+      dockerfile-path: backend/deploy_config/nginx/Dockerfile
+      working-directory: ./backend
+      additional-labels: |
+        org.opencontainers.image.licenses=MIT
+        org.opencontainers.image.description=Image with custom Nginx configuration
+      tags: |
+        type=sha  
 
-    outputs:
-      backend_image_tag: ${{ steps.meta-backend-image.outputs.tags }}
-      nginx_image_tag: ${{ steps.meta-nginx-image.outputs.tags }}
+  # build-push-image:
+  #   runs-on:
+  #     ubuntu-latest
 
-    defaults:
-      run:
-        shell: sh
-        working-directory: ./backend
+  #   outputs:
+  #     backend_image_tag: ${{ steps.meta-backend-image.outputs.tags }}
+  #     nginx_image_tag: ${{ steps.meta-nginx-image.outputs.tags }}
 
-    permissions:
-      contents: read
-      packages: write
-      attestations: write
-      id-token: write
+  #   defaults:
+  #     run:
+  #       shell: sh
+  #       working-directory: ./backend
 
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
+  #   permissions:
+  #     contents: read
+  #     packages: write
+  #     attestations: write
+  #     id-token: write
 
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
 
-      - name: Extract Metadata for Docker Backend image
-        id: meta-backend-image
-        uses: docker/metadata-action@v5
-        with:
-          images: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.BACKEND_IMAGE_NAME }}
-          labels: |
-            org.opencontainers.image.licenses=MIT
-            org.opencontainers.image.description=Image with backend and frontend implementation for proxy management
-          tags: |
-            type=sha
+  #     - name: Set up Docker Buildx
+  #       uses: docker/setup-buildx-action@v3
 
-      - name: Login to GitHub Container Registry
-        if: github.event_name != 'pull_request'
-        uses: docker/login-action@v3
-        with:
-          registry: ${{ env.REGISTRY }}
-          username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
+  #     - name: Extract Metadata for Docker Backend image
+  #       id: meta-backend-image
+  #       uses: docker/metadata-action@v5
+  #       with:
+  #         images: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.BACKEND_IMAGE_NAME }}
+  #         labels: |
+  #           org.opencontainers.image.licenses=MIT
+  #           org.opencontainers.image.description=Image with backend and frontend implementation for proxy management
+  #         tags: |
+  #           type=sha
 
-      - name: Build and push Backend image
-        uses: docker/build-push-action@v6
-        with:
-          context: backend
-          file: backend/Dockerfile
-          push: ${{ github.event_name != 'pull_request' }}
-          tags: ${{ steps.meta-backend-image.outputs.tags }}
-          labels: ${{ steps.meta-backend-image.outputs.labels }}
-          cache-to: type=gha
-          cache-from: type=gha
+  #     - name: Login to GitHub Container Registry
+  #       if: github.event_name != 'pull_request'
+  #       uses: docker/login-action@v3
+  #       with:
+  #         registry: ${{ env.REGISTRY }}
+  #         username: ${{ github.actor }}
+  #         password: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Extract Metadata for Docker Nginx image
-        id: meta-nginx-image
-        uses: docker/metadata-action@v5
-        with:
-          images: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.NGINX_IMAGE_NAME }}
-          labels: |
-            org.opencontainers.image.licenses=MIT
-            org.opencontainers.image.description=Image with custom Nginx configuration
-          tags: |
-            type=sha
+  #     - name: Build and push Backend image
+  #       uses: docker/build-push-action@v6
+  #       with:
+  #         context: backend
+  #         file: backend/Dockerfile
+  #         push: ${{ github.event_name != 'pull_request' }}
+  #         tags: ${{ steps.meta-backend-image.outputs.tags }}
+  #         labels: ${{ steps.meta-backend-image.outputs.labels }}
+  #         cache-to: type=gha
+  #         cache-from: type=gha
 
-      - name: Build and push Nginx image
-        uses: docker/build-push-action@v6
-        with:
-          context: backend/deploy_config/nginx
-          file: backend/deploy_config/nginx/Dockerfile
-          push: ${{ github.event_name != 'pull_request' }}
-          tags: ${{ steps.meta-nginx-image.outputs.tags }}
-          labels: ${{ steps.meta-nginx-image.outputs.labels }}
-          cache-to: type=gha
-          cache-from: type=gha
+  #     - name: Extract Metadata for Docker Nginx image
+  #       id: meta-nginx-image
+  #       uses: docker/metadata-action@v5
+  #       with:
+  #         images: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.NGINX_IMAGE_NAME }}
+  #         labels: |
+  #           org.opencontainers.image.licenses=MIT
+  #           org.opencontainers.image.description=Image with custom Nginx configuration
+  #         tags: |
+  #           type=sha
+
+  #     - name: Build and push Nginx image
+  #       uses: docker/build-push-action@v6
+  #       with:
+  #         context: backend/deploy_config/nginx
+  #         file: backend/deploy_config/nginx/Dockerfile
+  #         push: ${{ github.event_name != 'pull_request' }}
+  #         tags: ${{ steps.meta-nginx-image.outputs.tags }}
+  #         labels: ${{ steps.meta-nginx-image.outputs.labels }}
+  #         cache-to: type=gha
+  #         cache-from: type=gha
 
   pre-deploy:
+    env:
+      BRANCH: main
+
     needs:
       - setup-ssh
-      - build-push-image
+      - build-push-backend-image
+      - build-push-nginx-image
 
     name: Pre-Deploy to Staging
     runs-on: ubuntu-latest
@@ -149,8 +183,8 @@ jobs:
           ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
           cd ~/code/ProxyManagement/backend &&
 
-          export IMAGE_BACKEND_TAG=$(echo "${{ needs.build-push-image.outputs.backend_image_tag }}" | cut -d: -f2) &&
-          export IMAGE_NGINX_TAG=$(echo "${{ needs.build-push-image.outputs.nginx_image_tag }}" | cut -d: -f2) &&
+          export IMAGE_BACKEND_TAG=$(echo "${{ needs.build-push-backend-image.outputs.image-tag }}" | cut -d: -f2) &&
+          export IMAGE_NGINX_TAG=$(echo "${{ needs.build-push-nginx-image.outputs.image-tag }}" | cut -d: -f2) &&
 
           git checkout ${{ env.BRANCH }} &&
           git pull origin ${{ env.BRANCH }} &&
@@ -185,17 +219,17 @@ jobs:
         if: ${{ vars.ENABLED_UNDER_ATTACK == 'true' }}
         run: sleep 10 
           
-      - name: Health Check
-        run: |
-          response_code=$(curl -s -w "%{http_code}" -o /tmp/stage_health_response.json https://proxman.pp.ua/health_check)
-          if [ "$response_code" -ne 200 ]; then
-              echo "Health check failed with status $response_code"
-              exit 1
-          else
-              echo "Health check passed!"
-              echo "Server Health Status:"
-              cat /tmp/stage_health_response.json | jq
-          fi
+      # - name: Health Check
+      #   run: |
+      #     response_code=$(curl -s -w "%{http_code}" -o /tmp/stage_health_response.json https://proxman.pp.ua/health_check)
+      #     if [ "$response_code" -ne 200 ]; then
+      #         echo "Health check failed with status $response_code"
+      #         exit 1
+      #     else
+      #         echo "Health check passed!"
+      #         echo "Server Health Status:"
+      #         cat /tmp/stage_health_response.json | jq
+      #     fi
 
       - name: Enable Cloudflare Under Attack Mode
         if: ${{ vars.ENABLED_UNDER_ATTACK == 'true' }}
