update(docker-compose): updated `image` settings in `backend` and `db` services. Added `depends_on` to `nginx` service.
update(workflows): added env var `BRANCH, added outputs to `build-and=push` job, added some custom labels to the image being built. Added defaults to `pre-deploy` job. Updated `Pull Changes and Start Staging Server` step, commented out lines.

diff --git a/.github/workflows/pre_deploy.yml b/.github/workflows/pre_deploy.yml
--- a/.github/workflows/pre_deploy.yml
+++ b/.github/workflows/pre_deploy.yml
@@ -15,6 +15,7 @@ env:
   BACKEND_IMAGE_NAME: proxy_management
   NGINX_IMAGE_NAME: reverse_proxy
   REGISTRY: ghcr.io
+  BRANCH: main
   
 jobs:
   setup-ssh:
@@ -32,6 +33,10 @@ jobs:
   build-push-image:
     runs-on:
       ubuntu-latest
+
+    outputs:
+      backend_image_tag: ${{ steps.meta-backend-image.outputs.tags }}
+      nginx_image_tag: ${{ steps.meta-nginx-image.outputs.tags }}
 
     defaults:
       run:
@@ -53,7 +58,9 @@ jobs:
         uses: docker/metadata-action@v5
         with:
           images: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.BACKEND_IMAGE_NAME }}
-          labels: org.opencontainers.image.licenses=MIT
+          labels: 
+            org.opencontainers.image.licenses=MIT
+            org.opencontainers.image.description=Image with backend and frontend implementation for proxy management
           tags: |
             type=sha
 
@@ -79,7 +86,9 @@ jobs:
         uses: docker/metadata-action@v5
         with:
           images: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.NGINX_IMAGE_NAME }}
-          labels: org.opencontainers.image.licenses=MIT
+          labels: 
+            org.opencontainers.image.licenses=MIT
+            org.opencontainers.image.description=Image with custom Nginx configuration
           tags: |
             type=sha
 
@@ -99,6 +108,11 @@ jobs:
 
     name: Pre-Deploy to Staging
     runs-on: ubuntu-latest
+
+    defaults:
+      run:
+        shell: sh
+        working-directory: ./backend
 
     steps:
       - name: Download SSH Config Artifact
@@ -130,9 +144,20 @@ jobs:
 
       - name: Pull Changes and Start Staging Server
         run: |
-          cd ./backend/deploy_config
-          chmod +x start_staging_server.sh
-          ./start_staging_server.sh ${{ secrets.SSH_USER }} ${{ secrets.SSH_HOST }} ${{ secrets.WORK_DIR }} ${{ github.repository }}
+          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
+          sed -i 's/^IMAGE_BACKEND_TAG=.*/IMAGE_BACKEND_TAG=${{ needs.build-push-image.outputs.backend_image_tag }}/' .env &&
+          sed -i 's/^IMAGE_NGINX_TAG=.*/IMAGE_NGINX_TAG=${{ needs.build-push-image.outputs.nginx_image_tag }}/' .env &&
+          source .env &&
+          if docker secret ls --format '{{.Name}}' | grep -q "env_file"; then docker secret rm env_file; fi &&
+          docker secret create env_file .env &&
+          git checkout ${{ env.BRANCH }} &&
+          git pull origin ${{ env.BRANCH }} &&
+          docker stack deploy --compose-file docker-compose.yml fastapi --with-registry-auth
+          "
+
+          # cd ./backend/deploy_config
+          # chmod +x start_staging_server.sh
+          # ./start_staging_server.sh ${{ secrets.SSH_USER }} ${{ secrets.SSH_HOST }} ${{ secrets.WORK_DIR }} ${{ github.repository }}
 
       - name: Disable Cloudflare Under Attack Mode
         if: ${{ vars.ENABLED_UNDER_ATTACK == 'true' }}
@@ -142,37 +167,37 @@ jobs:
           cloudflare_zone_id: ${{ secrets.CLOUDFLARE_ZONE_ID }}
           api_key_cloudflare: ${{ secrets.API_KEY_CLOUDFLARE }}
 
-      - name: Wait for Server Startup
-        run: |
-          for i in {1..5}; do
-            response_code=$(curl -s -o /dev/null -w "%{http_code}" ${{ secrets.STAGE_BASE_URL }}/health_check)
-            if [ "$response_code" -eq 200 ]; then
-              echo "Server is up!"
-              break
-            fi
-            echo "Waiting for server..."
-            sleep 5
-          done
-          if [ "$response_code" -ne 200 ]; then
-            echo "Server did not start in time."
-            exit 1
-          fi
+      # - name: Wait for Server Startup
+      #   run: |
+      #     for i in {1..5}; do
+      #       response_code=$(curl -s -o /dev/null -w "%{http_code}" ${{ secrets.STAGE_BASE_URL }}/health_check)
+      #       if [ "$response_code" -eq 200 ]; then
+      #         echo "Server is up!"
+      #         break
+      #       fi
+      #       echo "Waiting for server..."
+      #       sleep 5
+      #     done
+      #     if [ "$response_code" -ne 200 ]; then
+      #       echo "Server did not start in time."
+      #       exit 1
+      #     fi
 
-      - name: Delay for Security Mode Change
-        if: ${{ vars.ENABLED_UNDER_ATTACK == 'true' }}
-        run: sleep 10 
+      # - name: Delay for Security Mode Change
+      #   if: ${{ vars.ENABLED_UNDER_ATTACK == 'true' }}
+      #   run: sleep 10 
           
-      - name: Health Check
-        run: |
-          response_code=$(curl -s -w "%{http_code}" -o /tmp/stage_health_response.json ${{ secrets.STAGE_BASE_URL }}/health_check)
-          if [ "$response_code" -ne 200 ]; then
-              echo "Health check failed with status $response_code"
-              exit 1
-          else
-              echo "Health check passed!"
-              echo "Server Health Status:"
-              cat /tmp/stage_health_response.json | jq
-          fi
+      # - name: Health Check
+      #   run: |
+      #     response_code=$(curl -s -w "%{http_code}" -o /tmp/stage_health_response.json ${{ secrets.STAGE_BASE_URL }}/health_check)
+      #     if [ "$response_code" -ne 200 ]; then
+      #         echo "Health check failed with status $response_code"
+      #         exit 1
+      #     else
+      #         echo "Health check passed!"
+      #         echo "Server Health Status:"
+      #         cat /tmp/stage_health_response.json | jq
+      #     fi
 
       - name: Enable Cloudflare Under Attack Mode
         if: ${{ vars.ENABLED_UNDER_ATTACK == 'true' }}
